name: "PR Title Checker"

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
  merge_group:

permissions:
  pull-requests: read

jobs:
  main:
    name: Validate PR title
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'merge_group' }}
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # Allow additional types beyond conventional commits
          types: |
            feat
            fix
            docs
            style
            refactor
            perf
            test
            build
            ci
            chore
            revert
            Fix
            Add
            Update
            Remove
          # Allow non-semantic titles that start with common prefixes
          requireScope: false
          disallowScopes: |
            release
            merge
          ignoreLabels: |
            bot
            dependencies
          validateSingleCommit: false